# Setup
title: Workshop on Secure, Private, and Fair Federated Optimization and Learning <br>
description: CAI Workshop 2025
baseurl:      "/Fairness-aware-Federated-Optimization-and-Learning"
paginate:     1
locale:       "en"

# About/contact
author:
  #name:       Author name
  url:       "https://xw00616.github.io/Fairness-aware-Federated-Optimization-and-Learning" 

#Others
navigation:
  Workshop: "index"
  Organizers: "organizers"
  Speakers: "speakers"
  Venue: "committee"
  Schedule: "schedule"
  Q&A: "question"
markdown: kramdown
